package hu.sms.views.layouts.AdminView;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminViewLayout extends VerticalLayout {
    protected VerticalLayout menuButtonsLayout;
    protected Label adminFelulet;
    protected VerticalLayout adminMenuBarLayout;
    protected HorizontalLayout alapadatokButton;
    protected Label alapadatokIcon;
    protected Label alapadatokLabel;
    protected HorizontalLayout intezmenyiAlapadatokButton;
    protected Label intezmenyiAlapadatokIcon;
    protected Label intezmenyiAlapadatokLabel;
    protected HorizontalLayout diakokKezeleseButton;
    protected Label diakokKezeleseIcon;
    protected Label diakokKezeleseLabel;
    protected HorizontalLayout osztalyokKezeleseButton;
    protected Label osztalyokKezeleseIcon;
    protected Label osztalyokKezeleseLabel;
    protected HorizontalLayout tantargyakKezeleseButton;
    protected Label tantargyakKezeleseIcon;
    protected Label tantargyakKezeleseLabel;
    protected HorizontalLayout orarendekKezeleseButton;
    protected Label orarendekKezeleseIcon;
    protected Label orarendekKezeleseLabel;
    protected Button visszaAFooldalraButton;
    protected Button uzenetekButton;
    protected Button beallitasokButton;
    protected VerticalLayout hitelugyletFobbAdatokLayout;
    protected Panel contentLayout;

    public AdminViewLayout() {
        Design.read(this);
    }
}
