package hu.sms.views.layouts;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminViewLayout extends VerticalLayout {
    protected VerticalLayout menuButtonsLayout;
    protected Label adminFelulet;
    protected VerticalLayout szerzodesInfoBarLayout;
    protected HorizontalLayout visszaASzerzodesreMenuButton;
    protected Label visszaASzerzodesreMenuIcon;
    protected Label visszaASzerzodesreMenuLabel;
    protected Button collapseMenuBar;
    protected VerticalLayout hitelugyletFobbAdatokLayout;
    protected Panel contentLayout;

    public AdminViewLayout() {
        Design.read(this);
    }
}
